[tool.poetry]
name = "rp-poetry"
version = "0.1.0"
description = ""
authors = ["Wajd Ali <wajd.ali.etu@univ-lille.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
