name: Pylint Checks

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install
        working-directory: ${{ github.workspace }}

      - name: Install Pylint
        run: |
          poetry add --dev pylint
        working-directory: ${{ github.workspace }}

      - name: Run Pylint
        run: poetry run pylint
